import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "../context/CartContext";
import CartSummary from "../components/CartSummary";
import Footer from "../components/Footer";

import ReduxProvider from "@/store/redux-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <header className="w-full flex items-center justify-between px-6 py-4 border-b bg-slate-100 shadow-sm fixed top-0 left-0 z-50">
            <h1 className="text-xl font-bold">Product Catalog</h1>
            <CartSummary />
          </header>
          <div className="pt-[72px] pb-[72px] h-screen overflow-y-auto">
            <ReduxProvider>{children}</ReduxProvider>
          </div>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
